/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as OSpecialisteRouteImport } from './routes/o-specialiste'
import { Route as PolitikaKonfidencialnostiRouteImport } from './routes/politika-konfidencialnosti'
import { Route as OtrasliObshchepitRouteImport } from './routes/otrasli.obshchepit'
import { Route as OtrasliPererabotkaRouteImport } from './routes/otrasli.pererabotka'
import { Route as OtrasliProizvodstvoRouteImport } from './routes/otrasli.proizvodstvo'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as UslugiAudityRouteImport } from './routes/uslugi.audity'
import { Route as UslugiDeklaraciiRouteImport } from './routes/uslugi.deklaracii'
import { Route as UslugiHaccpRouteImport } from './routes/uslugi.haccp'
import { Route as UslugiIso22000RouteImport } from './routes/uslugi.iso-22000'
import { Route as UslugiObuchenieRouteImport } from './routes/uslugi.obuchenie'
import { Route as UslugiPpkRouteImport } from './routes/uslugi.ppk'
import { Route as UslugiTuRouteImport } from './routes/uslugi.tu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const OSpecialisteRoute = OSpecialisteRouteImport.update({
  id: '/o-specialiste',
  path: '/o-specialiste',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaKonfidencialnostiRoute =
  PolitikaKonfidencialnostiRouteImport.update({
    id: '/politika-konfidencialnosti',
    path: '/politika-konfidencialnosti',
    getParentRoute: () => rootRouteImport,
  } as any)
const OtrasliObshchepitRoute = OtrasliObshchepitRouteImport.update({
  id: '/otrasli/obshchepit',
  path: '/otrasli/obshchepit',
  getParentRoute: () => rootRouteImport,
} as any)
const OtrasliPererabotkaRoute = OtrasliPererabotkaRouteImport.update({
  id: '/otrasli/pererabotka',
  path: '/otrasli/pererabotka',
  getParentRoute: () => rootRouteImport,
} as any)
const OtrasliProizvodstvoRoute = OtrasliProizvodstvoRouteImport.update({
  id: '/otrasli/proizvodstvo',
  path: '/otrasli/proizvodstvo',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/uslugi/',
  path: '/uslugi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiAudityRoute = UslugiAudityRouteImport.update({
  id: '/uslugi/audity',
  path: '/uslugi/audity',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiDeklaraciiRoute = UslugiDeklaraciiRouteImport.update({
  id: '/uslugi/deklaracii',
  path: '/uslugi/deklaracii',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiHaccpRoute = UslugiHaccpRouteImport.update({
  id: '/uslugi/haccp',
  path: '/uslugi/haccp',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIso22000Route = UslugiIso22000RouteImport.update({
  id: '/uslugi/iso-22000',
  path: '/uslugi/iso-22000',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiObuchenieRoute = UslugiObuchenieRouteImport.update({
  id: '/uslugi/obuchenie',
  path: '/uslugi/obuchenie',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiPpkRoute = UslugiPpkRouteImport.update({
  id: '/uslugi/ppk',
  path: '/uslugi/ppk',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiTuRoute = UslugiTuRouteImport.update({
  id: '/uslugi/tu',
  path: '/uslugi/tu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/o-specialiste': typeof OSpecialisteRoute
  '/politika-konfidencialnosti': typeof PolitikaKonfidencialnostiRoute
  '/otrasli/obshchepit': typeof OtrasliObshchepitRoute
  '/otrasli/pererabotka': typeof OtrasliPererabotkaRoute
  '/otrasli/proizvodstvo': typeof OtrasliProizvodstvoRoute
  '/uslugi/audity': typeof UslugiAudityRoute
  '/uslugi/deklaracii': typeof UslugiDeklaraciiRoute
  '/uslugi/haccp': typeof UslugiHaccpRoute
  '/uslugi/iso-22000': typeof UslugiIso22000Route
  '/uslugi/obuchenie': typeof UslugiObuchenieRoute
  '/uslugi/ppk': typeof UslugiPpkRoute
  '/uslugi/tu': typeof UslugiTuRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/o-specialiste': typeof OSpecialisteRoute
  '/politika-konfidencialnosti': typeof PolitikaKonfidencialnostiRoute
  '/otrasli/obshchepit': typeof OtrasliObshchepitRoute
  '/otrasli/pererabotka': typeof OtrasliPererabotkaRoute
  '/otrasli/proizvodstvo': typeof OtrasliProizvodstvoRoute
  '/uslugi/audity': typeof UslugiAudityRoute
  '/uslugi/deklaracii': typeof UslugiDeklaraciiRoute
  '/uslugi/haccp': typeof UslugiHaccpRoute
  '/uslugi/iso-22000': typeof UslugiIso22000Route
  '/uslugi/obuchenie': typeof UslugiObuchenieRoute
  '/uslugi/ppk': typeof UslugiPpkRoute
  '/uslugi/tu': typeof UslugiTuRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/o-specialiste': typeof OSpecialisteRoute
  '/politika-konfidencialnosti': typeof PolitikaKonfidencialnostiRoute
  '/otrasli/obshchepit': typeof OtrasliObshchepitRoute
  '/otrasli/pererabotka': typeof OtrasliPererabotkaRoute
  '/otrasli/proizvodstvo': typeof OtrasliProizvodstvoRoute
  '/uslugi/audity': typeof UslugiAudityRoute
  '/uslugi/deklaracii': typeof UslugiDeklaraciiRoute
  '/uslugi/haccp': typeof UslugiHaccpRoute
  '/uslugi/iso-22000': typeof UslugiIso22000Route
  '/uslugi/obuchenie': typeof UslugiObuchenieRoute
  '/uslugi/ppk': typeof UslugiPpkRoute
  '/uslugi/tu': typeof UslugiTuRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakty'
    | '/o-specialiste'
    | '/politika-konfidencialnosti'
    | '/otrasli/obshchepit'
    | '/otrasli/pererabotka'
    | '/otrasli/proizvodstvo'
    | '/uslugi/audity'
    | '/uslugi/deklaracii'
    | '/uslugi/haccp'
    | '/uslugi/iso-22000'
    | '/uslugi/obuchenie'
    | '/uslugi/ppk'
    | '/uslugi/tu'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakty'
    | '/o-specialiste'
    | '/politika-konfidencialnosti'
    | '/otrasli/obshchepit'
    | '/otrasli/pererabotka'
    | '/otrasli/proizvodstvo'
    | '/uslugi/audity'
    | '/uslugi/deklaracii'
    | '/uslugi/haccp'
    | '/uslugi/iso-22000'
    | '/uslugi/obuchenie'
    | '/uslugi/ppk'
    | '/uslugi/tu'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/kontakty'
    | '/o-specialiste'
    | '/politika-konfidencialnosti'
    | '/otrasli/obshchepit'
    | '/otrasli/pererabotka'
    | '/otrasli/proizvodstvo'
    | '/uslugi/audity'
    | '/uslugi/deklaracii'
    | '/uslugi/haccp'
    | '/uslugi/iso-22000'
    | '/uslugi/obuchenie'
    | '/uslugi/ppk'
    | '/uslugi/tu'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktyRoute: typeof KontaktyRoute
  OSpecialisteRoute: typeof OSpecialisteRoute
  PolitikaKonfidencialnostiRoute: typeof PolitikaKonfidencialnostiRoute
  OtrasliObshchepitRoute: typeof OtrasliObshchepitRoute
  OtrasliPererabotkaRoute: typeof OtrasliPererabotkaRoute
  OtrasliProizvodstvoRoute: typeof OtrasliProizvodstvoRoute
  UslugiAudityRoute: typeof UslugiAudityRoute
  UslugiDeklaraciiRoute: typeof UslugiDeklaraciiRoute
  UslugiHaccpRoute: typeof UslugiHaccpRoute
  UslugiIso22000Route: typeof UslugiIso22000Route
  UslugiObuchenieRoute: typeof UslugiObuchenieRoute
  UslugiPpkRoute: typeof UslugiPpkRoute
  UslugiTuRoute: typeof UslugiTuRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-specialiste': {
      id: '/o-specialiste'
      path: '/o-specialiste'
      fullPath: '/o-specialiste'
      preLoaderRoute: typeof OSpecialisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-konfidencialnosti': {
      id: '/politika-konfidencialnosti'
      path: '/politika-konfidencialnosti'
      fullPath: '/politika-konfidencialnosti'
      preLoaderRoute: typeof PolitikaKonfidencialnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otrasli/obshchepit': {
      id: '/otrasli/obshchepit'
      path: '/otrasli/obshchepit'
      fullPath: '/otrasli/obshchepit'
      preLoaderRoute: typeof OtrasliObshchepitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otrasli/pererabotka': {
      id: '/otrasli/pererabotka'
      path: '/otrasli/pererabotka'
      fullPath: '/otrasli/pererabotka'
      preLoaderRoute: typeof OtrasliPererabotkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otrasli/proizvodstvo': {
      id: '/otrasli/proizvodstvo'
      path: '/otrasli/proizvodstvo'
      fullPath: '/otrasli/proizvodstvo'
      preLoaderRoute: typeof OtrasliProizvodstvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/uslugi'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/audity': {
      id: '/uslugi/audity'
      path: '/uslugi/audity'
      fullPath: '/uslugi/audity'
      preLoaderRoute: typeof UslugiAudityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/deklaracii': {
      id: '/uslugi/deklaracii'
      path: '/uslugi/deklaracii'
      fullPath: '/uslugi/deklaracii'
      preLoaderRoute: typeof UslugiDeklaraciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/haccp': {
      id: '/uslugi/haccp'
      path: '/uslugi/haccp'
      fullPath: '/uslugi/haccp'
      preLoaderRoute: typeof UslugiHaccpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/iso-22000': {
      id: '/uslugi/iso-22000'
      path: '/uslugi/iso-22000'
      fullPath: '/uslugi/iso-22000'
      preLoaderRoute: typeof UslugiIso22000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/obuchenie': {
      id: '/uslugi/obuchenie'
      path: '/uslugi/obuchenie'
      fullPath: '/uslugi/obuchenie'
      preLoaderRoute: typeof UslugiObuchenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/ppk': {
      id: '/uslugi/ppk'
      path: '/uslugi/ppk'
      fullPath: '/uslugi/ppk'
      preLoaderRoute: typeof UslugiPpkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/tu': {
      id: '/uslugi/tu'
      path: '/uslugi/tu'
      fullPath: '/uslugi/tu'
      preLoaderRoute: typeof UslugiTuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktyRoute: KontaktyRoute,
  OSpecialisteRoute: OSpecialisteRoute,
  PolitikaKonfidencialnostiRoute: PolitikaKonfidencialnostiRoute,
  OtrasliObshchepitRoute: OtrasliObshchepitRoute,
  OtrasliPererabotkaRoute: OtrasliPererabotkaRoute,
  OtrasliProizvodstvoRoute: OtrasliProizvodstvoRoute,
  UslugiAudityRoute: UslugiAudityRoute,
  UslugiDeklaraciiRoute: UslugiDeklaraciiRoute,
  UslugiHaccpRoute: UslugiHaccpRoute,
  UslugiIso22000Route: UslugiIso22000Route,
  UslugiObuchenieRoute: UslugiObuchenieRoute,
  UslugiPpkRoute: UslugiPpkRoute,
  UslugiTuRoute: UslugiTuRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
